### ISSUE TITLE
Implement event expiry mechanism from Zino 1

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/zino#190] opened 2024-03-20 12:30 UTC
Zino 1 enforces an expiry timer for events that have been closed.  Once an event expires, it is entirely evicted from Zino's running state, but not before saving a copy of it in a separate history file (one file per event, IIRC).  I believe Zino 1 refers to this eviction process as "scavenging" in parts of the code.

Some things that need to be clarified:

- [ ] What is Zino 1's expiry time for events?
- [ ] Where does Zino 1 save on-disk representations of scavenged events?

**Comment by johannaengland** [comment] 2024-03-20 13:03
Duplicate of #182.

**Closed by johannaengland** 2024-03-20 13:03 UTC
Labels: duplicate
